#!/bin/zsh

# Author: Shuhei Hayakawa

#_______________________________________________________________________________
function i()
{
    if [ "$1" ]; then
	history 1000 | grep "$@"
    else
	history 30
    fi
}

#_______________________________________________________________________________
function I()
{
    if [ "$1" ]; then
	history  | grep "$@"
    else
	history 30
    fi
}

#_______________________________________________________________________________
function env_grep()
{
    if [ "$1" ]; then
	printenv | grep "$@"
    else printenv
    fi
}
alias env="env_grep"

#_______________________________________________________________________________
# function tree {
#     if [ "$1" ]; then tree -L "$@"; else tree ; fi
# }
# alias tr=tree

#_______________________________________________________________________________
function path_remove()
{
    export PATH=`echo -n $PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`
}

function path_append() { path_remove $1; export PATH="$PATH:$1"; }
function path_prepend() { path_remove $1; export PATH="$1:$PATH"; }

#_______________________________________________________________________________
function ldpath_remove()
{
    export LD_LIBRARY_PATH=`echo -n $LD_LIBRARY_PATH | awk -v RS=: -v ORS=: '$0 != "'$1'"' | sed 's/:$//'`
}

function ldpath_append() { ldpath_remove $1; export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$1"; }
function ldpath_prepend() { ldpath_remove $1; export LD_LIBRARY_PATH="$1:$LD_LIBRARY_PATH"; }
