#!/bin/zsh

# Author: Shuhei Hayakawa

#______________________________________________________________________________
host=
if [ ! -z "$HOSTNAME" ]; then host=$HOSTNAME; fi
if [ ! -z "$HOST"     ]; then host=$HOST;     fi

case $host in
    km*) ;;
    hyp*) ;;
    lambda*) ;;
    shpc*)
	alias which='alias | /bin/which --tty-only --read-alias --show-dot --show-tilde'
	case $host in
	    shpc2*)
		alias kek="ssh hayashu@login.cc.kek.jp"
		;;
	    *)
		alias kek="ssh -t hayashu@sshcc1.kek.jp ssh hayashu@ccw07.cc.kek.jp"
		;;
	esac
	alias ss=$HOME/local/bin/ss.sh
	alias root='root -l'
	export G4WORKDIR=$HOME/work/geant4
	export G4TOP=/sw/geant4/10.5.0
	cd $G4TOP/bin && source geant4.sh && cd - >/dev/null
	cd $G4TOP/share/Geant4-10.5.0/geant4make && source geant4make.sh && cd - >/dev/null
	case $host in
	    *.k18net)
		export http_proxy=http://k18server:8080
		export https_proxy=http://k18server:8080
		;;
	    *)
		;;
	esac
	;;
    shmb*|dhcp*)
	source /usr/local/bin/thisroot.sh
	export PATH=/usr/local/bin:/usr/local/sbin:$PATH
	export PATH=/usr/local/opt/coreutils/libexec/gnubin:$PATH
	export PATH=/usr/local/opt/gnu-which/libexec/gnubin:$PATH
	export PATH=$(npm bin):$PATH
	alias echo='gecho'
	alias ls="ls -F --color --group-directories-first"
	alias open="reattach-to-user-namespace open"
	alias readlink='greadlink'
	G4TOP=/usr/local/opt/geant4
	prev=$PWD
	cd $G4TOP/bin && source geant4.sh 2>/dev/null
	cd $G4TOP/share/Geant4-*/geant4make && source geant4make.sh 2>/dev/null
	cd $prev
	export G4WORKDIR=$HOME/work/geant4
	export PATH=$PATH:$G4WORKDIR/bin/Darwin-g++
	export PATH=$PATH:$HOME/software/dawn:/usr/local/opt/qt/bin
	export QTHOME=/usr/local/opt/qt
	export QTLIBPATH=/usr/local/opt/qt/lib
	alias root="root -l"
	case $host in
	    *.intra.j-parc.jp)
		cd ~/.ssh && ln -sf config_inside config
		;;
	    *)
		cd ~/.ssh && ln -sf config_outside config
		;;
	esac
	alias kek='ssh -AY ccw07.cc.kek.jp'
	cd
	;;
    ccw*)
	ulimit -u unlimited
	ulimit -n 4096
	# export LIBGL_ALWAYS_INDIRECT=1
	module load gcc/830
	module load git/2260
	module load python/3.7 2>/dev/null
	source /group/had/sks/software/root/6.22.02/bin/thisroot.sh
	source /opt/python-3.7/etc/profile.d/conda.sh
	export PATH=/group/had/sks/software/unpacker/unpacker.gcc830/bin:$PATH
	alias cmake=cmake3

	### Geant4
	export G4VERSION=10.6.2
	export G4TOP=/sw/packages/geant4/$G4VERSION-mt
	prev=$PWD
	cd $G4TOP/bin && source geant4.sh
	cd $G4TOP/share/Geant4-$G4VERSION/geant4make && source geant4make.sh
	cd $prev
	export G4WORKDIR=$HOME/work/geant4
	export PATH=$HOME/local/bin:$G4WORKDIR/bin/Linux-g++:$PATH

	# export PATH=/group/had/sks/software/anaconda2/bin:$PATH
	# export LD_LIBRARY_PATH=/group/had/sks/software/anaconda2/lib:$LD_LIBRARY_PATH

	##### Python for Emulsion analysis
	# kinema=1
	if [ "$kinema" = 1 ]; then
	    echo "load kinema"
	    export PATH=/group/had/sks/software/pyenv/shims:$PATH
	    export PATH=/group/had/sks/software/pyenv/bin:$PATH
	    export PATH=/group/had/sks/software/shims:$PATH
	    export PYENV_ROOT=/group/had/sks/software/pyenv
	    eval "$(pyenv init -)"
	    export PATH=$PYENV_ROOT/bin:$PATH
	    alias python=/group/had/sks/software/pyenv/bin/python
	else
	    # source /opt/rh/python27/enable
	    # source /opt/rh/rh-python35/enable
	fi
	# export PYTHONWARNINGS=ignore
	# PYTHONPATH=/group/had/sks/software/anaconda2/lib/python2.7/site-packages:$PYTHONPATH
	# PYTHONPATH=$PYTHONPATH:/group/had/sks/software/pyenv/versions/2.7.13/lib/python2.7/site-packages

	# ldpath_remove /lib64
	# ldpath_remove /usr/lib64
	# ldpath_remove /usr/local/lib
	;;
    *)
	alias kek="ssh -t hayashu@sshcc1.kek.jp ssh login.cc.kek.jp"
	;;
esac
