#!/bin/zsh

# Author: Shuhei Hayakawa

#_______________________________________________________________________________
host=
if [ ! -z "$HOSTNAME" ]; then host=$HOSTNAME; fi
if [ ! -z "$HOST"     ]; then host=$HOST;     fi

case $host in
    km*) ;;
    hyp*) ;;
    shpc*)
	alias kek=$HOME/local/bin/kek.sh
	alias ss=$HOME/local/bin/ss.sh
	source $HOME/software/root/v6.09.02/bin/thisroot.sh
	alias root='root -l'
	G4WORKDIR=$HOME/work/geant4
	G4TOP=$HOME/software/geant4/9.6.4
	cd $G4TOP/bin && source geant4.sh && cd - >/dev/null
	cd $G4TOP/share/Geant4-9.6.4/geant4make && source geant4make.sh && cd - >/dev/null
	case $host in
	    *.k18net)
		export http_proxy=http://k18server:8080
		export https_proxy=http://k18server:8080
		;;
	    *)
		;;
	esac
	;;
    shmbp*)
	export PATH=/usr/local/opt/coreutils/bin:/usr/local/bin:$PATH
	alias ls="gls -F --color --group-directories-first"
	alias open="reattach-to-user-namespace open"
	alias readlink='greadlink'
	alias which='alias | gwhich --tty-only --read-alias --show-dot --show-tilde'
	export G4WORKDIR=$HOME/work/geant4
	export PATH=$PATH:$G4WORKDIR/bin/Linux-g++
	export PATH=$PATH:$HOME/software/dawn
	export XERCESCROOT=$HOME/software/xerces
	alias root="root -l"
	case $host in
	    *.intra.j-parc.jp)
		alias kek='sshpass -f ~/private/pass_phrase ssh -Y hayashu@login.cc.kek.jp'
		;;
	    *)
		alias kek='sshpass -f ~/private/pass_phrase ssh -Y -t hayashu@sshcc1.kk.jp "sshpass -f ~/private/pass_phrase ssh -Y login.cc.kek.jp"'
		;;
	esac
	;;
    cw*)
	if has module; then
	    module load gcc/485
	    source ~/.thisroot.sh
	    alias root="root -l"
	fi
	G4TOP=/sw/packages/geant4/9.6.4
	prev=$PWD
	cd $G4TOP/bin && source geant4.sh
	cd $G4TOP/share/Geant4-9.6.4/geant4make && source geant4make.sh
	cd $prev
	G4WORKDIR=$HOME/geant4
	PATH=$G4WORKDIR/bin/Linux-g++:$HOME/software/unpacker/pro/bin:$PATH
	export LD_LIBRARY_PATH=/opt/gcc-4.8.5/lib64:$LD_LIBRARY_PATH
	;;
    *) ;;
esac
