#!/bin/zsh

# Author: Shuhei Hayakawa

#_______________________________________________________________________________
#echo " read .bash_aliases ..." >2

alias rm="rm -iv"
alias rmr="\rm -rfv"
alias mv="mv -iv"
alias cp="cp -iv"
alias j="jobs -l"
alias du="du -csh"
alias ..="cd .."

alias ls="ls -F --color --group-directories-first"
alias la="ls -A"
alias ll="ls -lh"
alias lla="ls -Alh"
alias l.='ls -d .??*'
alias ll.="ls -dlh .??*"
alias l="ls"
alias lx="ls -BhX"
alias lk="ls -lhSr"
alias lc="ls -lhtr"
alias less="less -iMR"

alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"

alias lpr="lpr -o PageSize=A4 -Pshuhei_mono"
alias lprc="\lpr -o PageSize=A4 -Pshuhei_color"
alias lprcd="\lpr -o PageSize=A4 -o Duplex=DuplexNoTumble -Pshuhei_color"

alias vi=vim
alias emacs="emacs -nw"
alias em="emacs"
alias sem="sudo emacs -nw"
alias emb="emacs ~/.bashrc"
alias ems="emacs --script"
alias mew="emacs -f mew"
alias www="emacs -f w3m"
#alias om="cd ~/work/opera-3d;~/software/Opera_13_039/bin/opera_manager &"

alias od="od -tx4z -Ax -v"

alias sz="source ~/.zshrc"
alias pl="~/local/bin/pl"
alias logw="sudo /root/logw"
alias h=which
alias cal="~/software/jhcal/jhcal"
alias q="exit"

alias ss="ssh -Y shuhei@kmpc5.phys.sci.osaka-u.ac.jp"
#alias saho="ssh -XY shuhei@login-a.rcnp.osaka-u.ac.jp"
