#!/bin/zsh

# Author: Shuhei Hayakawa

#_______________________________________________________________________________
host=
if [ ! -z "$HOSTNAME" ]; then host=$HOSTNAME; fi
if [ ! -z "$HOST"     ]; then host=$HOST;     fi

case $host in
    km*) ;;
    hyp*) ;;
    shpc*)
	case $host in
	    *.intra.j-parc.jp)
		alias kek="ssh hayashu@cw01.cc.kek.jp"
		;;
	    *)
		alias kek="ssh -t hayashu@sshcc1.kek.jp ssh hayashu@cw01.cc.kek.jp"
		;;
	esac
	alias ss=$HOME/local/bin/ss.sh
	alias root='root -l'
	G4WORKDIR=$HOME/work/geant4
	G4TOP=$HOME/software/geant4/9.6.4
	cd $G4TOP/bin && source geant4.sh && cd - >/dev/null
	cd $G4TOP/share/Geant4-9.6.4/geant4make && source geant4make.sh && cd - >/dev/null
	case $host in
	    *.k18net)
		export http_proxy=http://k18server:8080
		export https_proxy=http://k18server:8080
		;;
	    *)
		;;
	esac
	;;
    shmbp*)
	export PATH=/usr/local/opt/coreutils/bin:/usr/local/bin:$PATH
	alias ls="gls -F --color --group-directories-first"
	alias open="reattach-to-user-namespace open"
	alias readlink='greadlink'
	alias which='alias | gwhich --tty-only --read-alias --show-dot --show-tilde'
	G4TOP=/usr/local/opt/geant4
	#G4TOP=$HOME/software/geant4/9.6.4
	prev=$PWD
	cd $G4TOP/bin && source geant4.sh
	cd $G4TOP/share/Geant4-*/geant4make && source geant4make.sh
	cd $prev
	export G4WORKDIR=$HOME/work/geant4
	export PATH=$PATH:$G4WORKDIR/bin/Linux-g++
	export PATH=$PATH:$HOME/software/dawn
	#export XERCESCROOT=$HOME/software/xerces
	alias root="root -l"
	case $host in
	    *.intra.j-parc.jp)
		alias kek='ssh -Y hayashu@login.cc.kek.jp'
		;;
	    *)
		alias kek='sshpass -f ~/private/pass_phrase ssh -Y -t hayashu@sshcc1.kk.jp "sshpass -f ~/private/pass_phrase ssh -Y login.cc.kek.jp"'
		;;
	esac
	;;
    cw*)
	ulimit -u unlimited
	ulimit -n 4096
	if has module; then
	    module load gcc/485
	    source /sw/packages/root/new/bin/thisroot.sh
	    alias root="root -l"
	fi
	G4VERSION=10.4.0
	G4TOP=/sw/packages/geant4/$G4VERSION
	prev=$PWD
	cd $G4TOP/bin && source geant4.sh
	cd $G4TOP/share/Geant4-$G4VERSION/geant4make && source geant4make.sh
	cd $prev
	G4WORKDIR=$HOME/geant4
	export PATH=$G4WORKDIR/bin/Linux-g++:$PATH
	export PATH=$HOME/software/unpacker/pro/bin:$PATH
	ldpath_remove /usr/lib64
	ldpath_remove /usr/local/lib
	;;
    *)
	alias kek="ssh -t hayashu@sshcc1.kek.jp ssh cw01.cc.kek.jp"
	;;
esac
