#!/bin/zsh

# Author: Shuhei Hayakawa

#_______________________________________________________________________________
function has()
{
    type $1 >/dev/null 2>&1
}

#_______________________________________________________________________________
bindkey -e
stty quit undef

unset autologout
setopt auto_cd
setopt auto_pushd
setopt pushd_ignore_dups
setopt no_flow_control
setopt no_beep
autoload -Uz compinit
compinit

#_______________________________________________________________________________
# complist

zmodload zsh/complist
bindkey -M menuselect '^n' down-line-or-history
bindkey -M menuselect '^p' up-line-or-history

setopt auto_list
setopt auto_menu
setopt list_packed
setopt list_types
setopt noautoremoveslash
bindkey -r '^T'
bindkey "^[[Z" reverse-menu-complete
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' '+m:{A-Z}={a-z}'
zstyle ':completion:*:default' menu select=1

setopt extended_glob
unsetopt caseglob

#_______________________________________________________________________________
# history

HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
setopt bang_hist
setopt extended_history
setopt hist_ignore_dups
setopt share_history
setopt hist_reduce_blanks

autoload history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^P" history-beginning-search-backward-end
bindkey "^N" history-beginning-search-forward-end

autoload -U colors; colors

#_______________________________________________________________________________
export EDITOR=emacs
export PAGER="less -iMR"
export LESS='-X -i -P ?f%f:(stdin).  ?lb%lb?L/%L..  [?eEOF:?pb%pb\%..]'
export LESSOPEN='|src-hilite-lesspipe.sh %s'
export LSCOLORS=ExGxcxdxcxegedabagacad
export ZLS_COLORS=$LS_COLORS
export CLICOLOR=true
#zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

export JLESSCHARSET=japanese-ujis
export MANPATH=$MANPATH:/opt/local/man
export LD_LIBRARY_PATH=$HOME/local/lib:/usr/local/lib:$LD_LIBRARY_PATH

#_______________________________________________________________________________
if [ $PWD = /Home/pchome/shuhei ]; then cd ~; fi

# history
function sharehist {
    history -a
    history -c
    history -r
}
PROMPT_COMMAND='sharehist'
HISTSIZE=100000
HISTFILESIZE=100000
#HISTIGNORE=l:ls:la:ll:lk:lx:lc:l.:ll.:lla:i:I:..:cd:px:.q:-:+:=:sb:ss:hs:kek:ta
export HISTTIMEFORMAT='%y-%m-%d [%H:%M] '
export HISTCONTROL=ignoreboth
#shopt -s histappend
#shopt -s histreedit
#shopt -s histverify


#_______________________________________________________________________________
other_source=(
    ~/.zsh_aliases
    ~/.zsh_functions
    ~/.zsh_host
)
for f in $other_source; do
    if [ -f $f ]; then source $f; fi
done

#_______________________________________________________________________________
host=
if [ ! -z "$HOSTNAME" ]; then host=$HOSTNAME; fi
if [ ! -z "$HOST"     ]; then host=$HOST;     fi
case $host in
    km*) color=green;;
    hyp*) color=red;;
    shpc*) color=cyan;;
    shmbp*) color=magenta;;
    shwin*) color=cyan;;
    cw*) color=yellow;;
    *) color=white;;
esac

PROMPT="[%n@%B%{${fg[$color]}%}%m%{${reset_color}%}%b:%.] "
#RPROMPT="%{${fg[green]}%}%~%{${reset_color}%}"
TERM=xterm

km=shuhei@kmpc5.phys.sci.osaka-u.ac.jp
kek=hayashu@login.cc.kek.jp

#_______________________________________________________________________________
_path=""
for _p in $(echo $PATH | tr ':' ' '); do
  case ":${_path}:" in
    *:"${_p}":* )
      ;;
    * )
      if [ "$_path" ]; then
        _path="$_path:$_p"
      else
        _path=$_p
      fi
      ;;
  esac
done

export PATH=$_path
unset _p
unset _path

#_______________________________________________________________________________
_path=""
for _p in $(echo $LD_LIBRARY_PATH | tr ':' ' '); do
  case ":${_path}:" in
    *:"${_p}":* )
      ;;
    * )
      if [ "$_path" ]; then
        _path="$_path:$_p"
      else
        _path=$_p
      fi
      ;;
  esac
done
export LD_LIBRARY_PATH=$_path

unset _p
unset _path

#has tmux && [[ -z "$TMUX" && ! -z "$PS1" ]] && tmux && exit

#_______________________________________________________________________________
#  EOF
