#!/bin/bash

# Author: Shuhei Hayakawa

#______________________________________________________________________________
echo bashrc
ulimit -c 0
umask 022 # default 644
set color
#set -o ignoreeof
set history=50000
set histfilesize=50000
unset autologout

export EDITOR=emacs
export PAGER=less
export G4VRMLFILE_VIEWER=freewrl
export LESS='-iMR'
export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LSCOLORS=ExGxcxdxcxegedabagacad
export MANPATH=$MANPATH:$HOME/local/share/man
export PATH=$HOME/local/bin:/usr/local/bin:$PATH
export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH

km=shuhei@kmpc5.phys.sci.osaka-u.ac.jp
kek=hayashu@login.cc.kek.jp

#--- Terminal and prompt conf. ---
if [ $PWD != $HOME ]; then cd ~; fi

shopt -s no_empty_cmd_completion
shopt -s checkhash

export HISTSIZE=100000
export HISTFILESIZE=100000
export HISTIGNORE=l:ls:la:ll:lk:lx:lc:l.:ll.:lla:\
i:I:..:cd:px:.q:-:+:=:sb:ss:hs:kek:ta:fg
export HISTTIMEFORMAT='%y-%m-%d [%H:%M] '
export HISTCONTROL=ignoreboth
shopt -s histappend
shopt -s histreedit
shopt -s histverify
#---

case "$HOSTNAME" in
    km*) col=32;; # green
    hyp*) col=31;; # red
    hayakawa*) col="36";; # water
    shpc*) col=36;; # water
    *) col=1;; # white
esac

h2=`expr $HOSTNAME : '\(...\).*'`
u2=`expr $USER : '\(...\).*'`

#--- Other source ---
src=(
    /etc/bashrc
    $HOME/.bash_aliases
    $HOME/.bash_functions
    $HOME/.bash_host
)

for s in ${src[@]}; do
    if [ -f $s ]; then . $s; fi
done

#PS1="[\u@\h \W]$ "

export PATH=/usr/local/bin:$PATH
export EPICS_HOST_ARCH=linux-arm
export PATH=$PATH:$HOME/k18epics/base/bin/$EPICS_HOST_ARCH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/k18epics/base/lib/$EPICS_HOST_ARCH
export EPICS_CA_AUTO_ADDR_LIST=NO
export EPICS_CA_ADDR_LIST=192.168.30.255
